In [2]:
import numpy as np
import sklearn
import pandas as pd
import joblib
import pickle

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
#import gensim


from sklearn.metrics import classification_report, f1_score, confusion_matrix,recall_score,precision_score,make_scorer
from sklearn.model_selection import StratifiedKFold, train_test_split, learning_curve,cross_val_score
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from statistics import mean, stdev
import lightgbm as lgb

In [3]:
tweets_label_test_df = pd.read_csv("clean_tweets_labelled_test.csv")
X_test,y_test=tweets_label_test_df["clean_data"],tweets_label_test_df["label"]
tweets_label_test_df

label                                         clean_data
0         2                                         could help
1         2                  got first dose covid vaccin happi
2         2  receiv second dose vaccin yesterday side effec...
3         1  begin review russia vaccin putin say million d...
4         2                                 countri play polit
...     ...                                                ...
1795      1  dr jee mani peopl like get covaxin vaccin done...
1796      2  happi fulli vaccin covid readi serv manila phi...
1797      1  serum institut india announc cost covishield v...
1798      0              mine yesterday abl get bed today feel
1799      1  smart sympathi attend oblong noth educ feedbac...

[1800 rows x 2 columns]

### ML models


#### SGD 

In [18]:
# Load the model from the file
SGD_from_joblib = joblib.load('model/ml/SGD_tfidf_vectorizer4.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator SGDClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [19]:
# tfidf vectorizer transformation 
tfidf_obj = joblib.load('model/vect/_tfidf_vect_proxy_labelled4.pkl')
print(type(tfidf_obj))

X_test = tfidf_obj.transform(X_test.astype('U'))

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


<class 'sklearn.feature_extraction.text.TfidfVectorizer'>


C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [20]:

# Calculate the Score 
score = SGD_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 67.33 %


### Random Forest 

In [21]:
# Load the model from the file
RF_from_joblib = joblib.load('model/ml/random_forest_tfidf_vectorizer4.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [22]:
# Calculate the Score 
score = RF_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 65.44 %


### SVM

In [23]:
# Load the model from the file
SVM_from_joblib = joblib.load('model/ml/svm_tfidf_vectorizer3.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator SVC from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [24]:
# Calculate the Score 
score = SVM_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 66.39 %


### Naivye Bayes

In [25]:
# Load the model from the file
NB_from_joblib = joblib.load('model/ml/naive_bayes_tfidf_vectorizer4.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator MultinomialNB from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [26]:
# Calculate the Score 
score = NB_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 66.17 %


### KNN

In [28]:
# Load the model from the file
KNN_from_joblib = joblib.load('model/ml/KNeighborsClassifier_tfidf_vectorizer4.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [29]:
# Calculate the Score 
score = KNN_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 62.94 %


### Logistic Regression 

In [30]:
# Load the model from the file
LR_from_joblib = joblib.load('model/ml/logistic_regression_tfidf_vectorizer4.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [31]:
# Calculate the Score 
score = LR_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 67.11 %


### Decision Tree  

In [32]:
# Load the model from the file
DT_from_joblib = joblib.load('model/ml/DecisionTreeClassifier_tfidf_vectorizer4.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [33]:
# Calculate the Score 
score = DT_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 60.89 %


### Deep learning models

In [9]:
# Load the model from the file
#lstm_from_joblib = joblib.load('lstm_best_model.h5')

import gensim.downloader as api
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import backend as K
import keras
import tensorflow as tf
max_words = 5000
max_len = 200

n_epochs = 8
#tokenizer = Tokenizer(num_words=max_words)
#tokenizer.fit_on_texts(tweets_label_test_df["clean_data"].values.astype('U'))
#sequences = tokenizer.texts_to_sequences(tweets_label_test_df["clean_data"].values.astype('U'))
#tweets = pad_sequences(sequences, maxlen=max_len)

tokenizer = joblib.load('model/vect/dl_tokenizer2.pkl')
print(type(tokenizer))

sequences = tokenizer.texts_to_sequences(tweets_label_test_df["clean_data"].values.astype('U'))
tweets = pad_sequences(sequences, maxlen=max_len)

print(tweets)

labels = tf.keras.utils.to_categorical(tweets_label_test_df["label"], dtype="float32")

model = tf.keras.models.load_model('model/dl/lstm_best_model2.h5')

<class 'keras_preprocessing.text.Tokenizer'>
[[   0    0    0 ...    0  137  134]
 [   0    0    0 ...   10    1  265]
 [   0    0    0 ... 4213  958  291]
 ...
 [   0    0    0 ...  456  869  184]
 [   0    0    0 ...  654    6   16]
 [   0    0    0 ...  576 1697 4498]]


In [4]:
test_loss, test_acc = model.evaluate(tweets, labels, verbose=2)
print('Model accuracy: ',test_acc)

57/57 - 1s - loss: 0.9751 - accuracy: 0.6489
Model accuracy:  0.648888885974884


In [5]:
bilstm_model = keras.models.load_model('model/dl/bi_lstm_best_model2.h5')

In [6]:
test_loss, test_acc = bilstm_model.evaluate(tweets, labels, verbose=2)
print('Model accuracy: ',test_acc)

57/57 - 2s - loss: 1.0000 - accuracy: 0.6467
Model accuracy:  0.6466666460037231


In [7]:
gru_model = keras.models.load_model('model/dl/gru_best_model2.h5')

In [8]:
test_loss, test_acc = gru_model.evaluate(tweets, labels, verbose=2)
print('Model accuracy: ',test_acc)

57/57 - 1s - loss: 0.9290 - accuracy: 0.6600
Model accuracy:  0.6600000262260437


#### BERT

In [ ]:
import tensorflow_hub as hub


In [ ]:
ct_bert_saved_model = tf.keras.models.load_model(('model/bert/ct_bert_model.h5'),custom_objects={'KerasLayer':hub.KerasLayer})

In [ ]:
from  official.nlp.bert import tokenization

In [ ]:
%%time
 
bert_layer = hub.KerasLayer("https://tfhub.dev/digitalepidemiologylab/covid-twitter-bert/2", trainable=True)

In [ ]:
vocab_file = bert_layer.resolved_object.vocab_file.asset_path.numpy()
do_lower_case = bert_layer.resolved_object.do_lower_case.numpy()
tokenizer = tokenization.FullTokenizer(vocab_file, do_lower_case)

In [ ]:
def ct_bert_encode(texts, tokenizer, max_len=512):
    all_tokens = []
    all_masks = []
    all_segments = []
    
    for text in texts:
        text = tokenizer.tokenize(text)
            
        text = text[:max_len-2]
        input_sequence = ["[CLS]"] + text + ["[SEP]"]
        pad_len = max_len - len(input_sequence)
        
        tokens = tokenizer.convert_tokens_to_ids(input_sequence)
        tokens += [0] * pad_len
        pad_masks = [1] * len(input_sequence) + [0] * pad_len
        segment_ids = [0] * max_len
        
        all_tokens.append(tokens)
        all_masks.append(pad_masks)
        all_segments.append(segment_ids)
    
    return np.array(all_tokens), np.array(all_masks), np.array(all_segments)

In [ ]:
texts = tweets_label_test_df["clean_data"].astype('U')
target = labels

tweets = ct_bert_encode(texts, tokenizer, max_len=100)

In [ ]:
test_loss, test_acc = ct_bert_saved_model.evaluate(tweets, labels, verbose=2)
print('Model accuracy: ',test_acc)