In [22]:
import numpy as np
import sklearn
import pandas as pd
import joblib
import pickle

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
#import gensim


from sklearn.metrics import classification_report, f1_score, confusion_matrix,recall_score,precision_score,make_scorer
from sklearn.model_selection import StratifiedKFold, train_test_split, learning_curve,cross_val_score
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from statistics import mean, stdev
import lightgbm as lgb

In [23]:
tweets_label_test_df = pd.read_csv("clean_tweets_labelled_test.csv")
X_test,y_test=tweets_label_test_df["clean_data"],tweets_label_test_df["label"]

### ML models


#### SGD 

In [24]:
# Load the model from the file
SGD_from_joblib = joblib.load('model/ml/SGD_tfidf_vectorizer4.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator SGDClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [25]:
# tfidf vectorizer transformation 
tfidf_obj = joblib.load('model/vect/_tfidf_vect_proxy_labelled4.pkl')
print(type(tfidf_obj))

X_test = tfidf_obj.transform(X_test.astype('U'))

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


<class 'sklearn.feature_extraction.text.TfidfVectorizer'>


In [26]:

# Calculate the Score 
score = SGD_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 66.11 %


### Random Forest 

In [27]:
# Load the model from the file
RF_from_joblib = joblib.load('model/ml/random_forest_tfidf_vectorizer4.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [28]:
# Calculate the Score 
score = RF_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 65.94 %


### SVM

In [29]:
# Load the model from the file
SVM_from_joblib = joblib.load('model/ml/svm_tfidf_vectorizer4.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator SVC from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [30]:
# Calculate the Score 
score = SVM_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 68.50 %


### Naivye Bayes

In [31]:
# Load the model from the file
NB_from_joblib = joblib.load('model/ml/naive_bayes_tfidf_vectorizer4.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator MultinomialNB from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [32]:
# Calculate the Score 
score = NB_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 55.67 %


### KNN

In [33]:
# Load the model from the file
KNN_from_joblib = joblib.load('model/ml/KNeighborsClassifier_tfidf_vectorizer4.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [34]:
# Calculate the Score 
score = KNN_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 33.78 %


### Logistic Regression 

In [35]:
# Load the model from the file
LR_from_joblib = joblib.load('model/ml/logistic_regression_tfidf_vectorizer4.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [36]:
# Calculate the Score 
score = LR_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 66.17 %


### DT 

In [37]:
# Load the model from the file
DT_from_joblib = joblib.load('model/ml/DecisionTreeClassifier_tfidf_vectorizer4.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [38]:
# Calculate the Score 
score = DT_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 60.78 %


### Deep learning models

In [27]:
# Load the model from the file
#lstm_from_joblib = joblib.load('lstm_best_model.h5')

import gensim.downloader as api
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import backend as K
import tensorflow as tf
max_words = 5000
max_len = 200

n_epochs = 8
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(tweets_label_test_df["clean_data"].values.astype('U'))
sequences = tokenizer.texts_to_sequences(tweets_label_test_df["clean_data"].values.astype('U'))
tweets = pad_sequences(sequences, maxlen=max_len)
print(tweets)

labels = tf.keras.utils.to_categorical(tweets_label_test_df["label"], dtype="float32")

model = tf.keras.models.load_model('lstm_best_model4.h5')

[[   0    0    0 ...    0  153   93]
 [   0    0    0 ...    3    1  171]
 [   0    0    0 ... 1920  875  172]
 ...
 [   0    0    0 ...  236  298   66]
 [   0    0    0 ...  820   10   39]
 [   0    0    0 ... 3975 3976 1033]]


In [22]:
test_loss, test_acc = model.evaluate(tweets, labels, verbose=2)
print('Model accuracy: ',test_acc)

57/57 - 1s - loss: 1.8870 - accuracy: 0.5978
Model accuracy:  0.597777783870697


In [23]:
bilstm_model = keras.models.load_model('bi_lstm_best_model4.h5')

In [24]:
test_loss, test_acc = bilstm_model.evaluate(tweets, labels, verbose=2)
print('Model accuracy: ',test_acc)

57/57 - 2s - loss: 1.9903 - accuracy: 0.5911
Model accuracy:  0.5911111235618591


In [26]:
gru_model = keras.models.load_model('gru_best_model4.h5')

In [27]:
test_loss, test_acc = gru_model.evaluate(tweets, labels, verbose=2)
print('Model accuracy: ',test_acc)

57/57 - 1s - loss: 2.2894 - accuracy: 0.5961
Model accuracy:  0.5961111187934875


#### BERT

In [19]:
import tensorflow_hub as hub


In [20]:
ct_bert_saved_model = tf.keras.models.load_model(('ct_bert_model.h5'),custom_objects={'KerasLayer':hub.KerasLayer})

In [21]:
from  official.nlp.bert import tokenization

In [22]:
%%time
 
bert_layer = hub.KerasLayer("https://tfhub.dev/digitalepidemiologylab/covid-twitter-bert/2", trainable=True)

Wall time: 13.2 s


In [23]:
vocab_file = bert_layer.resolved_object.vocab_file.asset_path.numpy()
do_lower_case = bert_layer.resolved_object.do_lower_case.numpy()
tokenizer = tokenization.FullTokenizer(vocab_file, do_lower_case)

In [24]:
def ct_bert_encode(texts, tokenizer, max_len=512):
    all_tokens = []
    all_masks = []
    all_segments = []
    
    for text in texts:
        text = tokenizer.tokenize(text)
            
        text = text[:max_len-2]
        input_sequence = ["[CLS]"] + text + ["[SEP]"]
        pad_len = max_len - len(input_sequence)
        
        tokens = tokenizer.convert_tokens_to_ids(input_sequence)
        tokens += [0] * pad_len
        pad_masks = [1] * len(input_sequence) + [0] * pad_len
        segment_ids = [0] * max_len
        
        all_tokens.append(tokens)
        all_masks.append(pad_masks)
        all_segments.append(segment_ids)
    
    return np.array(all_tokens), np.array(all_masks), np.array(all_segments)

In [25]:
texts = tweets_label_test_df["clean_data"].astype('U')
target = labels

tweets = ct_bert_encode(texts, tokenizer, max_len=100)

In [26]:
test_loss, test_acc = ct_bert_saved_model.evaluate(tweets, labels, verbose=2)
print('Model accuracy: ',test_acc)

57/57 - 551s - loss: 1.9937 - accuracy: 0.6483
Model accuracy:  0.6483333110809326
