In [1]:
import numpy as np
import sklearn
import pandas as pd
import joblib
import pickle

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
#import gensim


In [2]:
tweets_label_test_df = pd.read_csv("clean_tweets_labelled_test.csv")
X_test,y_test=tweets_label_test_df["clean_data"],tweets_label_test_df["label"]

### ML models


#### SGD 

In [30]:
# Load the model from the file
SGD_from_joblib = joblib.load('model/ml/SGD_tfidf_vectorizer.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator SGDClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [31]:
# tfidf vectorizer transformation 
tfidf_obj = joblib.load('model/vect/_tfidf_vect_labelled.pkl')
print(type(tfidf_obj))

X_test = tfidf_obj.transform(X_test.astype('U'))

<class 'sklearn.feature_extraction.text.TfidfVectorizer'>


C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [32]:

# Calculate the Score 
score = SGD_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 66.78 %


### Random Forest 

In [33]:
# Load the model from the file
RF_from_joblib = joblib.load('model/ml/random_forest_tfidf_vectorizer.pkl')
print(type(RF_from_joblib))

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


<class 'sklearn.ensemble._forest.RandomForestClassifier'>


In [34]:
# Calculate the Score 
score = RF_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 67.56 %


### SVM

In [35]:
# Load the model from the file
SVM_from_joblib = joblib.load('model/ml/svm_tfidf_vectorizer.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator SVC from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [36]:
# Calculate the Score 
score = SVM_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 67.72 %


### Naivye Bayes

In [37]:
# Load the model from the file
NB_from_joblib = joblib.load('model/ml/naive_bayes_tfidf_vectorizer.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator MultinomialNB from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [38]:
# Calculate the Score 
score = NB_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 66.50 %


### KNN

In [39]:
# Load the model from the file
KNN_from_joblib = joblib.load('model/ml/KNeighborsClassifier_tfidf_vectorizer.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [40]:
# Calculate the Score 
score = KNN_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 61.50 %


### Logistic Regression 

In [41]:
# Load the model from the file
LR_from_joblib = joblib.load('model/ml/logistic_regression_tfidf_vectorizer.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [42]:
# Calculate the Score 
score = LR_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 68.22 %


### Decision Tree

In [43]:
# Load the model from the file
DT_from_joblib = joblib.load('model/ml/DecisionTreeClassifier_tfidf_vectorizer.pkl')

C:\Users\rkr\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.2 when using version 0.24.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [44]:
# Calculate the Score 
score = DT_from_joblib.score(X_test, y_test)  
# Print the Score
print("Test Accuracy score: {0:.2f} %".format(100 * score))  

Test Accuracy score: 62.06 %


### Deep learning models

In [12]:
# Load the model from the file
#lstm_from_joblib = joblib.load('lstm_best_model.h5')

import gensim.downloader as api
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import backend as K
import tensorflow as tf
import keras
max_words = 5000
max_len = 200

n_epochs = 8
from keras import backend as kb 



tokenizer = joblib.load('model/vect/dl_tokenizer.pkl')
print(type(tokenizer))


sequences = tokenizer.texts_to_sequences(tweets_label_test_df["clean_data"].values.astype('U'))
tweets = pad_sequences(sequences, maxlen=max_len)
print(tweets)

labels = tf.keras.utils.to_categorical(tweets_label_test_df["label"], dtype="float32")

model = keras.models.load_model('model/dl/lstm_best_model.h5')

<class 'keras_preprocessing.text.Tokenizer'>
[[   0    0    0 ...    0  160  120]
 [   0    0    0 ...    5    1  158]
 [   0    0    0 ... 2758  770  173]
 ...
 [   0    0    0 ...  274  549   98]
 [   0    0    0 ...  991   10   25]
 [   0    0    0 ... 1077 2950 3391]]


In [58]:
try:
    tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
    tf.config.experimental_connect_to_cluster(tpu)
    tf.tpu.experimental.initialize_tpu_system(tpu)
    strategy = tf.distribute.experimental.TPUStrategy(tpu)
    
except:
    strategy = tf.distribute.get_strategy()
    
print('Number of replicas in sync: ', strategy.num_replicas_in_sync)

Number of replicas in sync:  1


In [59]:
#! rm -rf ~/.nv

In [60]:
test_loss, test_acc = model.evaluate(tweets, labels, verbose=2)
print('Model accuracy: ',test_acc)

57/57 - 1s - loss: 0.8635 - accuracy: 0.6061
Model accuracy:  0.6061111092567444


In [61]:
bilstm_model = keras.models.load_model('model/dl/bi_lstm_best_model.h5')

In [62]:
test_loss, test_acc = bilstm_model.evaluate(tweets, labels, verbose=2)
print('Model accuracy: ',test_acc)

57/57 - 2s - loss: 0.8276 - accuracy: 0.6594
Model accuracy:  0.6594444513320923


In [63]:
gru_model = keras.models.load_model('model/dl/gru_best_model.h5')

In [64]:
test_loss, test_acc = gru_model.evaluate(tweets, labels, verbose=2)
print('Model accuracy: ',test_acc)

57/57 - 1s - loss: 0.8194 - accuracy: 0.6756
Model accuracy:  0.6755555272102356


In [6]:
import tensorflow_hub as hub

In [13]:
ct_bert_saved_model = tf.keras.models.load_model(('model/bert/ct_bert_model.h5'),custom_objects={'KerasLayer':hub.KerasLayer})


In [14]:
from  official.nlp.bert import tokenization

In [15]:
%%time
 
bert_layer = hub.KerasLayer("https://tfhub.dev/digitalepidemiologylab/covid-twitter-bert/2", trainable=True)

Wall time: 12.3 s


In [16]:
vocab_file = bert_layer.resolved_object.vocab_file.asset_path.numpy()
do_lower_case = bert_layer.resolved_object.do_lower_case.numpy()
tokenizer = tokenization.FullTokenizer(vocab_file, do_lower_case)

In [17]:
def ct_bert_encode(texts, tokenizer, max_len=512):
    all_tokens = []
    all_masks = []
    all_segments = []
    
    for text in texts:
        text = tokenizer.tokenize(text)
            
        text = text[:max_len-2]
        input_sequence = ["[CLS]"] + text + ["[SEP]"]
        pad_len = max_len - len(input_sequence)
        
        tokens = tokenizer.convert_tokens_to_ids(input_sequence)
        tokens += [0] * pad_len
        pad_masks = [1] * len(input_sequence) + [0] * pad_len
        segment_ids = [0] * max_len
        
        all_tokens.append(tokens)
        all_masks.append(pad_masks)
        all_segments.append(segment_ids)
    
    return np.array(all_tokens), np.array(all_masks), np.array(all_segments)

In [18]:
texts = tweets_label_test_df["clean_data"].astype('U')
target = labels

tweets = ct_bert_encode(texts, tokenizer, max_len=100)

In [19]:
test_loss, test_acc = ct_bert_saved_model.evaluate(tweets, labels, verbose=2)
print('Model accuracy: ',test_acc)

57/57 - 640s - loss: 0.9861 - accuracy: 0.6989
Model accuracy:  0.698888897895813
